### PR TITLE
Update "telegra.ph" to "graph.org"

### PR DESCRIPTION
**Pull request by New-dev0**
- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My addition is ordered alphabetically
- [x] My submission has a useful description
- [x] The description does not have more than 100 characters
- [x] The description does not end with punctuation
- [x] Each table column is padded with one space on either side
- [x] I have searched the repository for any relevant issues or pull requests
- [x] Any category I am creating has the minimum requirement of 3 items
- [x] All changes have been [squashed][squash-link] into a single commit

[telegra.ph](https://telegra.ph) results in timeout, [https://graph.org](graph.org) is another officially supported domain.

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by marcelscruz** [comment]
[telegra.ph](https://telegra.ph) seems to load normally, maybe that was just a hiccup in the server?
Alternatively, what about having both domains listed?

**Comment by New-dev0** [comment]
> [telegra.ph](https://telegra.ph) seems to load normally, maybe that was just a hiccup in the server? Alternatively, what about having both domains listed?

maybe it's something with country/location.
Capture2
I think, It will be better to list both domains.

**Comment by marcelscruz** [comment]
Yes, it seems like it, as I can open both URLs without problems.
Could you please amend the PR to include both?

**Review by marcelscruz — APPROVED** [review]

**Comment by marcelscruz** [comment]
Thank you!

**Pull request merged**
