### PR TITLE
Added Cohere and fixed issue #93

### PR DESCRIPTION
**Pull request by Shaurya50211**
- [X] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [X ] My addition is ordered alphabetically
- [X ] My submission has a useful description
- [ X] The description does not have more than 100 characters
- [X ] The description does not end with punctuation
- [ X] Each table column is padded with one space on either side
- [ X] I have searched the repository for any relevant issues or pull requests
- [X ] Any category I am creating has the minimum requirement of 3 items
- [X ] All changes have been [squashed][squash-link] into a single commit

[squash-link]: <https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit>

### CODE REVIEW

**Comment by marcelscruz** [comment]
Hi @Shaurya50211, thank you for the contribution.

Just a couple of things before we merge:

1. Does this service offer an API where developers could retrieve data? I just found their SDK after a quick look. If so, could you link to it instead?
2. Please keep the title of the project as it is.

Let me know if you have any questions.

**Comment by Shaurya50211** [comment]
Sure, I will change that

**Comment by Shaurya50211** [comment]
Did you mean https://docs.cohere.ai/ link?

**Comment by marcelscruz** [comment]
> Did you mean https://docs.cohere.ai/ link?

Sure, that works. Thank you!

**Comment by Shaurya50211** [comment]
Wait, what is wrong with the title and description?

**Comment by marcelscruz** [comment]
> Wait, what is wrong with the title and description?

For the moment I'd prefer to keep the title and description of the project as they are, as they're also used on the website.
In general, contributions to the resources are always welcome, but the project's information should remain as is.

Btw, I'm referring to this change here.
Screenshot 2023-02-15 at 16 01 45

**Comment by Shaurya50211** [comment]
Thanks for clarifying

**Comment by Shaurya50211** [comment]
Done!

**Comment by Shaurya50211** [comment]
I also fixed issue #93

**Comment by marcelscruz** [comment]
Thank you very much!

**Comment by Shaurya50211** [comment]
> Thank you very much!

My Pleasure!

**Pull request merged**
